sudo: false

language: python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script:
  - flake8 .

script:
  - python -m pytest tests/
  - coverage run -m pytest tests/

after_success:
- coveralls